zones:
  - zone_id: 'public-icon'
    zone_name: 'Public ICON mainnet'
    client_endpoint: 'https://ctz.solidwallet.io'
    storage_location: ''
  - zone_id: 'public-ethereum'
    zone_name: 'Public Ethereum mainnet'
    client_endpoint: ''
    storage_location: ''
